### ISSUE TITLE
'TypeError: undefined is not a function' when trying to look at the inbox

### ISSUE THREAD

**Issue by hanshasselberg** [wayneashleyberry/wunderlist-cli#40]
Hi,

this looks like a great project. I installed it, but there seems to be something wrong.

```
$ wunderline inbox
/usr/local/lib/node_modules/wunderline/util/get-inbox.js:22
    var lists = body.filter(function (item) {
                     ^
TypeError: undefined is not a function
    at Request._callback (/usr/local/lib/node_modules/wunderline/util/get-inbox.js:22:22)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

Thanks,
Hans

**Comment by wayneashleyberry** [comment]
Hi @i0rek, it looks like an authentication error, have you set up your `.wunderlinerc` file?

**Comment by hanshasselberg** [comment]
@wayneashleyberry yes.

```
cat ~/.wunderlinerc
{
  "client_id": "..........................",
  "access_token": "..............................."
}
```

**Comment by wayneashleyberry** [comment]
Just pushed a potential fix, would you mind installing `3.2.2`?

**Comment by hanshasselberg** [comment]
Thank you for the fast help! That doesn't fix my issue though:

```
$ wunderline --version
3.2.2
$ wunderline inbox
/usr/local/lib/node_modules/wunderline/util/get-inbox.js:22
    var lists = body.filter(function (item) {
                     ^
TypeError: undefined is not a function
    at Request._callback (/usr/local/lib/node_modules/wunderline/util/get-inbox.js:22:22)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by wayneashleyberry** [comment]
Strange... okay, i've added some extra debugging in `3.2.3`

If you could run `NODE_DEBUG=request wunderline inbox` and add the debugging output here that would really help :)

Looks like, for some reason, the API call to `/lists` is returning an empty body...

**Comment by hanshasselberg** [comment]
With debugging enabled I saw that I was unauthorised. I used the `client_secret` as `access_token`. Generating an access token fixed it.
Thanks!

**Comment by wayneashleyberry** [comment]
Oh cool - yeah, I need to add better error messages for that, will add it to my todo list :p
