### ISSUE TITLE
wunderline all: Cannot call method 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by juanpabloaj** [wayneashleyberry/wunderlist-cli#44]
If I try to use without make the configuration, I get this error

``` bash
$ npm install -g wunderline
$ wunderline all

TypeError: Cannot call method 'toUpperCase' of undefined
    at printList (/home/action/.parts/lib/node_modules/wunderline/util/print-list.js:66:30)
    at Array.forEach (native)
    at /home/action/.parts/lib/node_modules/wunderline/wunderline-all.js:14:8
    at /home/action/.parts/lib/node_modules/wunderline/util/get-lists.js:48:5
    at /home/action/.parts/lib/node_modules/wunderline/node_modules/async/lib/async.js:46:16
    at /home/action/.parts/lib/node_modules/wunderline/node_modules/async/lib/async.js:1248:30
    at /home/action/.parts/lib/node_modules/wunderline/util/get-lists.js:38:9
    at /home/action/.parts/lib/node_modules/wunderline/node_modules/async/lib/async.js:46:16
    at replenish (/home/action/.parts/lib/node_modules/wunderline/node_modules/async/lib/async.js:297:28)
    at /home/action/.parts/lib/node_modules/wunderline/node_modules/async/lib/async.js:317:29
```

**Comment by wayneashleyberry** [comment]
Hey @juanpabloaj, thanks for catching this bug. It should be fixed in [v3.3.0](https://github.com/we-are-next/wunderline/releases/tag/v3.3.0)

You can run the following command to update wunderline:

``` sh
npm i -g wunderline@latest
```

Please let me know if that helps :)
