### ISSUE TITLE
Unable to add task, getting an exception

### ISSUE THREAD

**Issue by ketanmujumdar** [wayneashleyberry/wunderlist-cli#50]
Hello,

I am getting the following exception while executing following command 

`wunderline add Hello, World!`

Exception: 

`````` /usr/local/lib/node_modules/wunderline/util/get-inbox.js:27
    var lists = body.filter(function (item) {
                     ^
TypeError: undefined is not a function
    at Request._callback (/usr/local/lib/node_modules/wunderline/util/get-inbox.js:27:22)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)```
``````

**Comment by ketanmujumdar** [comment]
Seems it was my issue, closing the ticket
