### ISSUE TITLE
Object #<Object> has no method 'filter'

### ISSUE THREAD

**Issue by krewmarco** [wayneashleyberry/wunderlist-cli#55]
TypeError: Object #<Object> has no method 'filter'
    at Request._callback (/usr/lib/node_modules/wunderline/util/get-inbox.js:29:22)
    at Request.self.callback (/usr/lib/node_modules/wunderline/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/wunderline/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/wunderline/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

> node -v
> v0.10.37

Ubuntu 12.04

> uname -a
> 3.13.0-48-generic #80~precise1-Ubuntu SMP Thu Mar 12 19:30:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wayneashleyberry** [comment]
hey @krewmarco, would you mind installing `4.0.1` and trying again?

**Comment by krewmarco** [comment]
I just installed 4.0.2 and it's working great.  Thanks!

Marco

**Comment by wayneashleyberry** [comment]
Awesome :) :balloon:
