### ISSUE TITLE
auth doesn't work

### ISSUE THREAD

**Issue by wkoszek** [wayneashleyberry/wunderlist-cli#62]
Auth doesn't work for me:

```
$ wunderline auth
Please create a Wunderlist Application before you proceed, you can do so over
here: https://developer.wunderlist.com/apps/new, once that is done please enter
your access token and client id below.
? CLIENT ID XXXXXXXX
? ACCESS TOKEN aaaasdasadsdasdjasodjasoijdoaisjdaijsodjasodijasodjasodijaodij
/usr/local/lib/node_modules/wunderline/wunderline-auth.js:47
    console.log('Thanks ' + body.name.split(' ')[0] + ', Wunderline has been a
                                     ^
TypeError: Cannot read property 'split' of undefined
    at Request._callback (/usr/local/lib/node_modules/wunderline/wunderline-auth.js:47:38)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1063:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

The `CLIENT ID` and `ACCESS TOKEN` are repasted from the website.

Then for login:

```
wunderline inbox
/usr/local/lib/node_modules/wunderline/lib/get-inbox.js:29
    var lists = body.filter(function (item) {
                     ^
TypeError: undefined is not a function
    at Request._callback (/usr/local/lib/node_modules/wunderline/lib/get-inbox.js:29:22)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1063:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by Thor77** [comment]
I get the same errors but i don't think the access-token is the problem.
It seems like these functions were removed/renamed from NodeJS.

**Comment by richipargo** [comment]
Same issue +1

**Comment by Thor77** [comment]
This issue is definitely not a problem with wunderline (except maybe proper error handling), it's a problem with your access token. After you click "CREATE ACCESS TOKEN" there will fade in a bar with this text: "Your access token for Wunderline Access is: [...] ", thats the token, you have to enter, not the client secret or whatever

**Comment by wkoszek** [comment]
@Thor77 I don't understand what you're saying. Let me explain once again:
1. I go to https://developer.wunderlist.com/apps
2. Create new app. Call it "cli". I put http://www.koszek.com as my URLs.
3. Double click Client ID string, CMD+A to select all, CMD+C to copy.
4.  In Terminal enter `wunderline auth`
5. I get:

```
wunderline auth
Please create a Wunderlist Application before you proceed, you can do so over
here: https://developer.wunderlist.com/apps/new, once that is done please enter
your access token and client id below.
? CLIENT ID
```

I paste the CLIENT ID string.
1. Go back to the browser
2. Double-click, CMD+A, CMD+C of the Client Secret
3. Switch back to terminal and paste the value in "CLIENT SECRET"
4. I get a crash from below.

What am I doing wrong? IMO everything is done correctly. I think it doesn't work.

```
/usr/local/lib/node_modules/wunderline/wunderline-auth.js:47
    console.log('Thanks ' + body.name.split(' ')[0] + ', Wunderline has been a
                                     ^
TypeError: Cannot read property 'split' of undefined
    at Request._callback (/usr/local/lib/node_modules/wunderline/wunderline-auth.js:47:38)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by wkoszek** [comment]
@Thor77  Ah, ok. I just clicked "CREATE ACCESS TOKEN" and it worked.

It's super confusing.

**Comment by geripgeri** [comment]
I had the same problem.
@wkoszek the CREATE ACCESS TOKEN" button solved the problem for me too! Thanks :thumbsup:
