### ISSUE TITLE
Any command that pulls back data fails, including Auth

### ISSUE THREAD

**Issue by CrowderSoup** [wayneashleyberry/wunderlist-cli#64]
I'm having an issue on multiple machines (Windows 10, Ubuntu 15.04). When I run `wunderline auth` and enter my apps credentials I get the following (on Windows 10, but I get the same on Ubuntu):

```
TypeError: Cannot call method 'split' of undefined
    at Request._callback (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\wunderline-auth.js:47:39)
    at Request.self.callback (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\node_modules\request\request.js:1082:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

It seems like it authenticates successfully though. Then when I run `wunderline inbox` I get:

```
TypeError: Object #<Object> has no method 'filter'
    at Request._callback (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\lib\get-inbox.js:29:22)
    at Request.self.callback (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\node_modules\request\request.js:1082:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\acrowder\AppData\Roaming\npm\node_modules\wunderline\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

If I can get some spare time I'll attempt to fork and fix, but in the meantime I wanted to submit an issue in case you were able to fix it more quickly than I can. Thanks!

**Comment by CrowderSoup** [comment]
Just tested again, issue seems to be resolved.
