### ISSUE TITLE
wunderline add crashes

### ISSUE THREAD

**Issue by AndreasOck** [wayneashleyberry/wunderlist-cli#65]
Hello,
I'm working with wunderline. It works fine. Except the "add" command crashes with the following error statement. I tried also on a raspberry pi. With the same error.
## Output in Windows 7:

C:\Users\aj>wunderline add Hello
C:\Users\aj\AppData\Roaming\npm\node_modules\wunderline\wunderline-add.js:146
        stdin().then(data => {
                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
## C:\Users\aj>

Do you have an idea?

**Comment by wayneashleyberry** [comment]
Which version of node are you running?

**Comment by AndreasOck** [comment]
Thank you, that's the solution. I update node to v5.1.0 and everything is ok!

**Comment by wayneashleyberry** [comment]
You're welcome :)
