### ISSUE TITLE
Add is broken

### ISSUE THREAD

**Issue by kavyasukumar** [wayneashleyberry/wunderlist-cli#70]
Fix for #61 seems to have broken add feature- both individual task as well as piped from stdin
### Direct add

``` bash
$ wunderline add test
/usr/local/lib/node_modules/wunderline/wunderline-add.js:146
        stdin().then(data => {
                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
### Piped stdin

``` bash
cat myfile.txt | wunderline add --stdin
/usr/local/lib/node_modules/wunderline/wunderline-add.js:146
        stdin().then(data => {
                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by kavyasukumar** [comment]
Sorry. This is duplicate of already addressed #65
